language: dart
dart:
  - stable
os:
  - linux
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
      # - fonts-droid

#install:
#  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis

#before_install:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

#before_script:
#  - cd ..
#  - git clone https://github.com/flutter/flutter.git
#  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
#  - flutter doctor

script:
  - cd $TRAVIS_BUILD_DIR
  - pub get
  - pub run test
  - pub global activate coverage
  - dart --observe=8111 test/domain/usecases/read_anime_details_test.dart
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- flutter packages get
  # - flutter analyze --no-pub --no-current-package lib
  #- flutter test
  # - flutter packages pub publish --dry-run
#before_deploy:
#  - chmod +x ./.travis/publish.sh # giving execution permissions to this file to avoid error 127.
#  - mv ./.travis ../ # moving this out the publication folder as we don't want to publish it.
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: '../.travis/publish.sh'
#  on:
#    tags: true

cache:
  directories:
    - $HOME/.pub-cache