name: anitube_crawler_api
description: Anitube website crawler API. This API allows you to get data and parse them
  from the brazilian anime website anitube.site.
version: 0.2.6+2
#author: Marcos Boaventura <scavenger.gnu@gmail.com>
homepage: https://github.com/sc4v3ng3r/anitube_crawler_api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  html: ^0.14.0+3
  
  #test_coverage: ^0.2.0

dev_dependencies:
  mockito: ^4.1.0
  test: ^1.5.1